name: DataSenderApp
options:
  deploymentTarget:
    iOS: "18.5"
  createIntermediateGroups: true
  bundleIdPrefix: com.cjsjca

configs:
  Debug:
    xcconfig:
      ENABLE_TESTABILITY: YES
  Release:
    xcconfig:
      ENABLE_TESTABILITY: NO

targets:
  DataSenderApp:
    type: application
    platform: iOS
    deploymentTarget: "18.5"
    sources:
      - path: Frontend
        name: DataSenderApp
        excludes:
          - "**/*.md"
      - path: Backend
        excludes:
          - "**/*.md"
          - MCP
    resources:
      - path: Assets.xcassets
      - path: Info.plist
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: DataSenderApp
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchStoryboardName: ""
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiredDeviceCapabilities:
          - armv7
        NSMicrophoneUsageDescription: "This app needs access to microphone to record audio."
        NSCameraUsageDescription: "This app needs access to camera to take photos."
        NSPhotoLibraryUsageDescription: "This app needs access to photo library to save photos."
    dependencies:
      - package: Supabase
      - package: DotEnv
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.cjsjca.DataSenderApp
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      INFOPLIST_FILE: Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      TARGETED_DEVICE_FAMILY: "1,2"
      SWIFT_VERSION: "5.0"
      CODE_SIGN_STYLE: Automatic
      GENERATE_INFOPLIST_FILE: NO

  DataSenderAppTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "18.5"
    sources:
      - path: Tests/UnitTests
      - path: DataSenderAppTests
        excludes:
          - "**/*.bak"
    dependencies:
      - target: DataSenderApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.cjsjca.DataSenderAppTests
      BUNDLE_LOADER: $(TEST_HOST)
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/DataSenderApp.app/DataSenderApp
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      GENERATE_INFOPLIST_FILE: YES
      SWIFT_VERSION: "5.0"
      CODE_SIGN_STYLE: Automatic
      TARGETED_DEVICE_FAMILY: "1,2"

  DataSenderAppUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "18.5"
    sources:
      - path: Tests/UITests
      - path: DataSenderAppUITests
    dependencies:
      - target: DataSenderApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.cjsjca.DataSenderAppUITests
      TEST_TARGET_NAME: DataSenderApp
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      GENERATE_INFOPLIST_FILE: YES
      SWIFT_VERSION: "5.0"
      CODE_SIGN_STYLE: Automatic
      TARGETED_DEVICE_FAMILY: "1,2"

packages:
  Supabase:
    url: https://github.com/supabase-community/supabase-swift.git
    from: 2.30.0
  DotEnv:
    url: https://github.com/swiftpackages/DotEnv.git
    from: 3.0.0

schemes:
  DataSenderApp:
    build:
      targets:
        DataSenderApp: all
    test:
      targets:
        - DataSenderAppTests
        - DataSenderAppUITests
      gatherCoverageData: true
    run:
      config: Debug
    archive:
      config: Release