name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}

jobs:
  build-and-test:
    name: Build & Test
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Xcode tests
        run: |
          xcodebuild test \
            -project DataSenderApp.xcodeproj \
            -scheme DataSenderApp \
            -destination "platform=iOS Simulator,name=iPhone 14,OS=18.5"

  supabase-integration:
    name: Supabase Integration Checks
    needs: build-and-test
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-supabase@v1
        with:
          version: 'latest'

      - name: Login to Supabase
        run: supabase login --token $SUPABASE_ACCESS_TOKEN

      - name: Link Supabase project
        run: supabase link --project-ref $SUPABASE_PROJECT_REF

      - name: List storage buckets
        run: supabase storage list-buckets

      - name: Run database query
        run: supabase db query "SELECT COUNT(*) FROM texts;"